### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by byzyk** [byzyk/hackerrank-practice#1]
**TODO list**
- [x] make sure Mocha only testing one folder
- [x] HR parser to be able to parse input, output, and code automatically using terminal (check if there is HR api for that) (see #2)
- [ ] build src files into a separate folder to be able to upload them straight to HR instead of copy/paste chunks of code
